import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/header/HeaderTop";
import HeaderMain from "@/components/header/HeaderMain";
import Navbar from "@/components/header/Navbar";
import { Toaster } from "sonner";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobileNav from "@/components/MobileNav";
import Footer from "@/components/Footer";
import Cart from "@/components/Cart";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Toaster position="top-center" richColors />
        <HeaderTop />
        <HeaderMain />
        <Cart />
        <Navbar />
        <MobileNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
